name: atomix
description: An elegant, simple and fast web framework.
version: 0.1.0+dev
repository: https://github.com/bryanbill/atomix

environment:
  sdk: ^3.4.1

dependencies:
  web: 0.5.1
  js: 0.7.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
