name: view
description: View is a Dart web library for building web user interfaces
version: 0.1.1+dev
repository: https://github.com/bryanbill/view

environment:
  sdk: ^3.4.1

dependencies:
  web: 0.5.1
  js: 0.7.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
