name: kitawi
description: kitawi is a Dart web library for building web user interfaces
version: 0.3.4
repository: https://github.com/kitawee/kitawi

environment:
  sdk: ^3.4.1
executables:
  kitawi:

dependencies:
  web: 0.5.1
  js: 0.7.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
