name: view_example
description: An example of how to use the view library.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  view:
    git:
      url: https://github.com/bryanbill/view.git
      ref: master

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
