# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: View release workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Add macOS and Windows
        dart-version: [stable] # You can add dev or specific versions here

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: ${{ matrix.dart-version }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Build for ${{ matrix.os }}
        run: |
          dart compile exe bin/view.dart -o build/view-${{ matrix.os }}

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: view-${{ matrix.os }}
          path: build/view-${{ matrix.os }}
