name: View release workflow

on:
  pull_request:
    branches: ["master"]

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Commit Message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - uses: actions/checkout@v4
      - name: Increment Version
        id: increment_version
        run: |
          # Get version from pubspec.yaml
          NEW_VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          # Set output
          echo "::set-output name=new_version::$NEW_VERSION"

  release:
    needs: [versioning]
    runs-on: ubuntu-latest
    

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.versioning.outputs.new_version }}
          release_name: Release ${{ needs.versioning.outputs.new_version }}
          body: |
            Release ${{ needs.versioning.outputs.new_version }}

